### ISSUE TITLE
TODO: CG & Game Dev

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#101]
https://github.com/Calinou/awesome-gamedev

### Book

- [ ] peter shirley 计算机图形学 
- [ ] 游戏编程权威 game coding complete
- [ ] 3D数学基础：图形与游戏开发
- [ ] 3D Math Primer for Graphics and Game Development
- [ ] Mathematics for 3D Game Programming & Computer Graphics 第二版
- [ ] https://book.douban.com/subject/1321769
- [ ] https://book.douban.com/subject/20282993
- [ ] [游戏设计模式](https://zhuanlan.zhihu.com/p/23821422)
- [ ] [Game Programmer Path](https://github.com/miloyip/game-programmer)

## Game Design

游戏设计之道 rogers
创造游戏中的艺术 omernick
游戏架构设计与策划基础 黄石
高级游戏设计技术 dormans

## D3D

Introduction to 3D Game Programming with DirectX 11
Practical Rendering & Computation with Direct3D 11

## Shader

Cg_tutorial
The Complete Effect and HLSL Guide
Shaders for Game Programmers and Artists
Advanced Lighting And Materials With Shaders
Programming Vertex, Geometry, and Pixel Shaders

## 地形

Real Time 3D Terrain Engines Using C++ And DX9

## Model and Animation

Advanced Animation with DirectX
Character Animation With Direct3D

## Physics

Game Physics
Game Physics Engine Development
Real-time Collision Detection

## LOD

Level of Detail for 3D Graphics

## AI

Programming Game AI by Example
Artificial Intelligence for Games
AI Game Engine Programming
AI Techniques for Game Programming

## Gems

Game Programming Gems
Game Engine Gems
GPU Gems
ShaderX/GPU Pro
AI Game Programming Wisdom

## Computer Graphics

- [ ] [图形控书单](https://zhuanlan.zhihu.com/p/27158983)

Interactive computer graphics : a top-down approach with shader-based OpenGL / Edward Angel
Coursera - 交互式计算机图形学 东京大学

### Geometry Processing

Computational Geometry: Algorithms and Applications. Third Edition. Mark de Berg

### Rendering

Physically Based Rendering, From Theory to Implementation /Matt Pharr
Real-Time Rendering, Tomas Akenine-Moller, Eric Haines & Naty Hoffman

### Animation and Simulation

Kim, Doyub. Fluid Engine Development. CRC Press, 2017
The Arts of Fluid Animation / Jos Stam CRC Press
Nonlinear Continuum Mechanics for Finite Element Analysis / Javier Bonet & Richard D. Wood
Rigid Body Simulation I & II / David Baraff

### Mathematics

Linear Algebra and Its Applications / Peter Lax
Modern Mathematics and Applications in Computer Graphics and Vision / Hongyu Guo

## Unity3D

- [ ] Coursera - Fudan University
- [ ] 慕课网
- [ ] 图书馆 317 625
- [ ] unity 游戏设计与实现 南梦宫
- [ ] unity UI 设计 simon jackson

## Unreal

- [ ] Udemy 2 Mooc

## CUDA/GPU Computing

- [ ] Udacity - UC Davis

## Game Engine

Game Engine Architecture, Jason Gregory
3D Game Engine Design, Second Edition
Pro OGRE 3D Programming
3D Game Engine Programming

渲染+建模+物流模拟+动画

1 绘制
1.1 真实感绘制(非实时)
1.1.1 光线追踪(Ray-tracing)
1.1.2 全局光照(Global Illumination)
1.2 实时绘制
1.2.1 Shading(BRDF, Programmable Shading等)
1.2.2 纹理(Texture Synthesis, 反走样, 采样等)
1.2.3 阴影和环境光照(Ambient Occlusion, Shadow Volume等)
1.2.4 基于图像的算法(HDR, Depth of Field, Motion Blur等)
1.2.5 光照算法(PRT, 球面谐波(Spherical Harmonic)等)
2 建模
2.1 曲面/曲线(Bézier曲线, B样条(B-Spline), 细分曲面(Subdivision Surface/Tessellation))
2.2 网格(Mesh)及形变(Morphing)
2.3 模型修复及重建(计算机视觉交叉方向)
3 物理模拟
3.1 刚体碰撞模拟
3.2 流体模拟(烟 火 水)
3.3 柔体模拟(布料 头发 皮肤 橡胶等)
4 动画
4.1 关键帧技术(keyframe)
4.2 基于物理的动画(Human motion capture, character animation等)

## Website

http://kesen.realtimerendering.com/
http://gdcvault.com/
http://www.gamedev.net/
http://www.gamasutra.com/
http://www.beyond3d.com/
http://www.gameres.com/
http://www.gamethk.com/
Nvidia和ATI的开发者中心 

## Documentary

- [ ] https://www.zhihu.com/question/27754707
- [ ] http://space.bilibili.com/6514957/#!/favlist?fid=61621195
- [ ] http://www.area5.tv/
- [ ] https://www.youtube.com/user/GyroVorbis

## Project

- [ ] http://graphicscodex.com/projects/projects/
