### ISSUE TITLE
TODO: C++ Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#103]
## Basis
- [ ] C++ Primer Plus
- [ ] C++ Primer

## Effective
- [ ] Effective C++
- [ ] More Effective C++
- [ ] Effective Modern C++ (C++11/14) (Animal Book)

## Exception

- [ ] Exceptional C++
- [ ] More Exceptional C++
- [ ] Exceptional C++ Style
## Templates and STL
- [ ] The C++ Standard Library: A Tutorial and Reference (2nd Edition)
- [ ] C++ Templates: The Complete Guide
## Concurrency
- [ ] C++ Concurrency
## Memory
- [ ] Memory Management: Algorithms and Implementation in C/C++
- [ ] Memory as a Programming Concept in C and C++

## Internal
- [ ] c++对象模型
- [ ] Modern C++ Design: Generic Programming and Design Patterns
