### ISSUE TITLE
TODO: System and Architecture Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#104]
## System Basis

- [ ] [Clean Code](https://book.douban.com/subject/3032825/)
- [ ] [Clean Ach](https://book.douban.com/subject/26915970/)
- [ ] [Designing Data-Intensive Applications](https://book.douban.com/subject/26197294/)
- [ ] 重构
- [ ] 代码大全
- [ ] [System Learning TOC](https://github.com/hollischuang/toBeTopJavaer)

## System Design

- [ ] [System Design Primer](https://github.com/donnemartin/system-design-primer)
- [ ] Domain-Driven Design
- [ ] [Raft Algorithm](https://raft.github.io)

## System Interviews

- [ ] [CS Notes](https://github.com/CyC2018/CS-Notes)

## C++ Basis

- [ ] C++ Primer Plus
- [ ] C++ Primer

## Effective C++

- [ ] Effective C++
- [ ] More Effective C++
- [ ] Effective Modern C++ (C++11/14) (Animal Book)

## C++ Exception

- [ ] Exceptional C++
- [ ] More Exceptional C++
- [ ] Exceptional C++ Style

## C++ Templates and STL

- [ ] The C++ Standard Library: A Tutorial and Reference (2nd Edition)
- [ ] C++ Templates: The Complete Guide

## C++ Concurrency

- [ ] C++ Concurrency

## C++ Memory Model

- [ ] Memory Management: Algorithms and Implementation in C/C++
- [ ] Memory as a Programming Concept in C and C++

## C++ Internal

- [ ] C++对象模型
- [ ] Modern C++ Design: Generic Programming and Design Patterns

**Comment by sabertazimi** [comment]
merged into #105
