### ISSUE TITLE
TODO : React Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#11]
## Testing
- [ ] https://daveceddia.com/getting-started-with-tdd-in-react/
## Book
- [ ] http://item.jd.com/11948386.html
## Best Practice
- [ ] https://github.com/lcxfs1991/blog
- [ ] https://github.com/krasimir/react-in-patterns/tree/master
- [ ] https://github.com/sorrycc/blog/issues/1
- [ ] Airbnb
### Tutorials
- [ ] https://twiknight.gitbooks.io/blog/content/index.html
- [ ] http://purplebamboo.github.io/2015/09/15/reactjs_source_analyze_part_one/
- [ ] [专栏 - purerender: React源码剖析系列](https://segmentfault.com/blog/purerender)
- [ ] https://github.com/acdlite/react-fiber-architecture
