### ISSUE TITLE
TODO: GItHub Following Tutorials

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#16]
Read the Tutorials provided by GitHub users followed by me

- [x] [xirong](https://github.com/xirong)
- [x] [waylau](https://github.com/waylau)
- [x] [RuanYiFeng](https://github.com/ruanyf)
- [x] [phodal](https://github.com/phodal)
