### ISSUE TITLE
TODO: Web Application

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#17]
Buy building a web application,learn web knowledge.
## Awesome App Idea
- [ ] api && spider
- [ ] spa third party Client netease music zhihu bilibili
- [ ] spa blog system
- [ ] text/rich/code editor
- [ ] jscraft
- [ ] news integration
### Basic 30 Days Challenge
- [x] https://javascript30.com/
### IFE Source Code Learning
-   [IFE](http://ife.baidu.com/)
### Shiyanlou Little  Proj Learning
-   [Font-End](https://www.shiyanlou.com/paths/web)
-   [Back-End](https://www.shiyanlou.com/paths/nodejs)
### Twitter Clone

- [ ] http://trysparkschool.com/

### Tmall Clone
- [ Tmall Clone - Part 1](http://www.imooc.com/learn/100)
- [Tmall Clone - Part 2](http://www.imooc.com/learn/148)
### Blog System
-   [Little Demo Trying](https://www.sitepoint.com/building-a-react-universal-blog-app-a-step-by-step-guide/)
-   [Multiple-Person Blog](http://wiki.jikexueyuan.com/project/express-mongodb-setup-blog/)
#### Basic
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/contentEditable
- [ ] https://developer.mozilla.org/en-US/docs/Rich-Text_Editing_in_Mozilla
#### Book
-   [Craft](http://www.finseth.com/craft/craft.pdf)
##### Summary
-   [ ] http://www.alloyteam.com/2015/09/intended-to-achieve-the-rich-text-editor/
-   [ ] [vzch's IDE](http://www.cppblog.com/vczh/category/14937.html)
-   [ ] [Design a Vim Editor](http://lists.suckless.org/dev/1409/23497.html)
-   [ ] [Code Mirror Workflow](http://marijnhaverbeke.nl/blog/codemirror-line-tree.html)
##### Part
-   [ ] [Selection](http://www.yi-jy.com/2013/06/22/%E6%96%87%E5%AD%97%E9%80%89%E4%B8%AD%E5%88%86%E4%BA%AB%E5%88%B0%E7%AE%80%E5%8D%95%E5%AE%9E%E7%8E%B0)
-   [ ] [iframe and execCommand](http://www.yi-jy.com/2015/01/21/%E5%AF%8C%E6%96%87%E6%9C%AC%E7%BC%96%E8%BE%91%E5%99%A8%E7%9A%84%E5%AE%9E%E7%8E%B0/)
-   [ ] [Syntax Highlighting](http://codemirror.net/1/story.html)
#### Samples
-   [ ] [React Rich Text Editor](https://github.com/ritzyed/ritzy)
-   [ ] [Terminal Vim Editor in Go](https://github.com/gchp/iota)
-   [ ] [Terminal Vim Editor in Python](https://github.com/jonathanslenders/pyvim)
-   [ ] [Emacs in JS](https://github.com/robrohan/9ne)
-   [ ] [Ymacs in JS](https://github.com/mishoo/ymacs)
-   [ ] [CodeMirror](https://github.com/codemirror/CodeMirror/tree/master/mode)
## Build with
- H5/CSS3/ES6
- Gulp/Webpack
- React
- Node
- Meteor
## Meteor
- [x] gitbook.io/meteor
- [x] http://wiki.jikexueyuan.com/project/discover-meteor/
