### ISSUE TITLE
TODO: Haskell Compiler

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#18]
## Target
- learn haskell
- learn compiler
## Learn by
- [ ] http://schemeworkshop.org/2006/11-ghuloum.pdf
- [ ] [Haskell Compiler](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/)
- [ ] http://www.stephendiehl.com/llvm/#code-generation-setup
