### ISSUE TITLE
TODO:Pro Git

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#22]
## GitHug Practice
- [ ] https://github.com/Gazler/githug
- [ ] https://github.com/git-tips/tips
## read the book Git/pro git
-   [ ] Chapter - Git工具(Advanced Feature)
  -   git shortlog 生成优雅(graceful)的CHANGLOG file
  -  git gc/git fsck  - 删除多余文件,压缩空间
  -  git filter-branch  - 删除多余文件,压缩空间
-   [ ] Chapter - 自定义Git(Advanced Config)
-  [ ] Chapter - Git内部原理与Git对象
  - pack object
  - loose object
  - tree object
  - blob object
  - commit object
## Advanced

https://github.com/Fmajor/gg

**Comment by sabertazimi** [comment]
Advanced Feature Left - move to Version 5.0
