### ISSUE TITLE
TODO: 鸟哥的Linux私房菜

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#24]
- [x] read the book Linux/book
- [x] ‌Traceroute
- [x] ipconfig
- [x] nslookup
- [x] htop/task manager
- [x] [Digital Ocean Cloud Server](https://www.digitalocean.com/)
- [x] [AWS VPN](https://www.webdigi.co.uk/blog/2015/how-to-setup-your-own-private-secure-free-vpn-on-the-amazon-aws-cloud-in-10-minutes/)
- [x] https://github.com/jlevy/the-art-of-command-line/blob/master/README-zh.md

**Comment by sabertazimi** [comment]
merge into #89
