### ISSUE TITLE
TODO: Compilers Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#25]
## Mooc
- [x] Compilers - USTC
## Book
- [x] https://wizardforcel.gitbooks.io/diy-c-compiler/content/

## Labs

- [ ] [DBN to SVG](https://github.com/kosamari/sbn)
- [ ] http://www.stephendiehl.com/llvm/
- [ ] [How to write a compiler](https://www.zhihu.com/question/36756224)
