### ISSUE TITLE
TODO: Operating Systems Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#27]
## Target

write a operating system lite
### Mooc
- [x] [QingHua Mooc](http://www.xuetangx.com/courses/course-v1:TsinghuaX+30240243X+2016_T1/about)
### Bran Kernel
- [x] [English Version](http://www.osdever.net/bkerndev/Docs/title.htm)
- [x] [Chinese Version](http://article.yeeyan.org/tags/%E5%86%85%E6%A0%B8%E3%80%81%E5%BC%80%E5%8F%91%E3%80%81%E6%95%99%E7%A8%8B)
### fleurer
- [x] http://fleurer-lee.com/paper.html
### ucore
- [x] https://chyyuu.gitbooks.io/ucorebook/content/
### hurlex
- [x] https://github.com/hurley25/hurlex-doc
- [x] http://web.archive.org/web/20130102094055/http://www.jamesmolloy.co.uk/tutorial_html/index.html

### xv6
- [ ] https://pdos.csail.mit.edu/6.828/2014/
- [ ] [Course Homepage](http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-828-operating-system-engineering-fall-2012/index.htm#)
- [ ] [Chinese Documentation](https://th0ar.gitbooks.io/xv6-chinese/content/)
- [ ] [Course Video](https://www.youtube.com/watch?v=kDRHsNauoxk&list=PLfciLKR3SgqNJKKIKUliWoNBBH1VHL3AP)

### Book
- [ ] Linux 0.11
### Samples
-   https://github.com/Fleurer/fleurix
-   https://github.com/LastAvenger/OS67
-   https://github.com/zellux/nexus
