### ISSUE TITLE
TODO: Online Judge

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#28]
- [x] [Job - leetcode](https://leetcode.com) https://githubQ.com/haoel/leetcode
- [x] [Codewars - haskell](http://codewars.com)
- [x] [Fun - galOJ](https://paiza.jp/poh/ando)
- [x] https://siddontang.gitbooks.io/leetcode-solution/content/array/remove_element.html

**Comment by sabertazimi** [comment]
Merge into #88
