### ISSUE TITLE
TODO: JavaScript Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#30]
## Basic
-   [x] js dom
-   [ ] /Web/JavaScript/book/js高级程序设计 2012
### Library
- [ ] https://github.com/ruanyf/es6tutorial ES 6 标准入门 2015
### Online
- [ ] http://www.open-open.com/lib/view/open1447222864319.html
- [ ] https://github.com/lukehoban/es6features
- [ ] https://leanpub.com/understandinges6/read/
- [ ] https://github.com/DrkSephy/es6-cheatsheet
#### Generator/yield
- [  ] http://greim.github.io/gen/dist/00-intro.html
#### promise
- [ ] https://zhuanlan.zhihu.com/p/21834559
- [ ] https://github.com/dollarshaveclub/postmate/blob/master/src/postmate.js
### Symbol
- [ ] https://rainsoft.io/detailed-overview-of-well-known-symbols/
## Deep
-   [ ] [Eloquent JavaScript 2016](http://eloquentjavascript.net/)
-   [ ] /Web/JavaScript/book/js good parts 2012
-   [ ] [Secrets of the JavaScript Ninja 2015](http://download.csdn.net/download/yannhack/8176911)
  -   [ ] https://github.com/yannhacking/ninja
-   [ ] [You don't know js 2015](https://github.com/getify/You-Dont-Know-JS)
## Tips
-   [ ] /Web/JavaScript/book/JavaScript启示录 2014
-   [ ] [You don't need jQuery](https://github.com/oneuijs/You-Dont-Need-jQuery)
-   [ ] http://youmightnotneedjquery.com/
## Style
-   [x] Maintable JS
-   [ ] https://github.com/airbnb/javascript
## Paradigm
- [ ] https://github.com/cht8687/You-Dont-Need-Lodash-Underscore
- [ ] https://github.com/timoxley/functional-javascript-workshop
- [ ] Object-Oriented JavaScript 2015
- [x] js函数式编程 tp312ja 1875
## Test
-   [ ] https://github.com/othiym23/bug-clinic
-   [ ] /Web/JS/book/test-driven-js
-   [x] /Web/JS/book/编写可测试的JavaScript 2015
### Frameworks
- [ ]   mocha + chai
- [ ]   Phantomjs
- [ ]   Karma
- [ ]   Slimerjs
### Libraries
- [ ]   mockery
- [ ]   istanbul(coverage analysis tool)
## Efficient
-   [x] Web/JavaScript/book/High Performance js 2013
-   [ ] http://mythbusters.js.org/index.html
-   [ ] https://www.youtube.com/watch?v=NthmeLEhDDM
-   [ ] Effective JavaScript 2015
-   [ ] 高性能网站建设指南 2015
-   [ ] 高性能网站建设进阶指南 2015
## Patterns
-   [ ] [es-observable](https://github.com/zenparsing/es-observable)
-   [x] [/Web/JS/book/js design patterns(online reading)](http://www.oschina.net/translate/learning-javascript-design-patterns?print)
-   [x] Book/js patterns

## Google

- [ ] https://developers.google.com/web/fundamentals/

### Basic
- [ ] [TCP/IP 1](https://book.douban.com/subject/1088054/)
- [ ] [TCP/IP 2](https://book.douban.com/subject/1087767/)
- [ ] [TCP/IP 3](https://book.douban.com/subject/1058634/)
### Need
- [ ] [Web安全深度剖析](https://book.douban.com/subject/26348894/)
- [ ] [精通脚本黑客](https://book.douban.com/subject/2112672/)
### Book
- [ ] https://github.com/evilcos/papers
- [ ] https://github.com/FallibleInc/security-guide-for-developers
### Advanced
- [ ] 白帽子讲Web安全
- [ ] Web前端黑客技术揭秘
- [ ] 黑客攻防技术宝典(第2版)
- [ ] XSS跨站脚本攻击剖析与防御
- [ ] SQL注入攻击与防御(第2版)
- [ ] Metasploit渗透测试指南
- [ ] Metasploit渗透测试魔鬼训练营
## Interview
- [ ] https://github.com/h5bp/Front-end-Developer-Interview-Questions
- [ ] https://github.com/HIT-Alibaba/interview
- [ ] https://github.com/hawx1993/Front-end-Interview-questions
## Full Stack
-   [ ] Polymer 面向未来的 Web 组件开发(Components)
-   [ ] 全端 Web 开发(JavaScript && Java)
## Definitive Guide
-   [ ] /Web/JavaScript/book/JavaScript权威指南
-   [ ] JavaScript 经典实例(cookbook)
-   [ ] Javascript & dhtml cookbook 2009
-   [ ] https://github.com/mrdavidlaing/javascript-koans
## API/Utils
-   [ ] jQuery Cookbook(Animal Book)
## List
-   [ ] https://github.com/fouber/blog
-   [ ] https://github.com/feross/standard
-   [ ] https://github.com/revolunet/JSbooks
