### ISSUE TITLE
TODO: JS-Books-Test

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#31]
-   [x] https://github.com/othiym23/bug-clinic
-   [x] /Web/JS/book/test-driven-js
-   [x] /Web/JS/book/编写可测试的JavaScript 2015
