### ISSUE TITLE
Bookmark: Winter Holiday Memo

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#34]
### TODO List

-   [x] Youtube - Samy Kambar
-   [x] IRC client

### Awesome-HTML5/CSS3-Demo

- [x]   http://tympanus.net/Development/AnimatedBooks/index2.html#
- [x]   https://www.zhihu.com/question/24398907

### Awesome-Workshop

- [x]   https://github.com/search?o=desc&q=workshop&s=stars&type=Repositories&utf8=%E2%9C%93

**Comment by sabertazimi** [comment]
Awesome-HTML5/CSS3-Demo

http://tympanus.net/Development/AnimatedBooks/index2.html#
