### ISSUE TITLE
TODO: Functional Language(Haskell) Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#35]
## FP List

https://github.com/bitemyapp/learnhaskell

## FP Basic
- [x] https://www.coursera.org/learn/programming-languages/home/welcome
-   [ ] [Online Real World Haskell](http://cnhaskell.com/)

## FP Data Structure and Algo

-   [ ] [Purely Functional Data Structures](https://book.douban.com/subject/1755557/)
-   [ ] [Pearls of Functional Algorithm Design](https://book.douban.com/subject/5290339/)

## FP Labs

-    [ ] [Type System](https://zhuanlan.zhihu.com/p/24181997)
-    [ ] [Stanford Assignments](http://www.scs.stanford.edu/14sp-cs240h/)
-    [ ] [CIS 194 Homework](http://www.seas.upenn.edu/~cis194/spring13/)
- [ ] http://tel.github.io/posts/mutable_algorithms_in_immutable_languges_part_1/
## FP Patterns
- [ ] https://github.com/gelisam/frp-zoo
## FP Advanced
-   [ ] Parallel and Concurrent Programming in Haskell
-   [ ] HUSTLYL/Haskell/books/etc
-   [ ] [Practice - H99](https://wiki.haskell.org/H-99:_Ninety-Nine_Haskell_Problems)
-   [ ] https://github.com/relevance/functional-koans
## FP Application
-   [ ] [Developing web applications with Haskell and Yesod](http://www.yesodweb.com/book-1.4)
-   [ ] https://github.com/yesodweb/yesod
-   [ ] http://elm-lang.org/
## FP Full Spec
- [ ] https://wiki.haskell.org/Typeclassopedia
## FP Tools
-   [ ] [Vim Haskell Workflow](http://www.stephendiehl.com/posts/vim_haskell.html)
## FP Perspective
-   利用好Monad和Applicative这两种Class
-   掌握State、((->) r)、Maybe、List、Cont等常用的数据类型
-   学习好parsec，很多parse类的事情就简单
-   Steve Awodey的蓝皮书，想学范畴论
-   读论文和背后的理论抽象
