### ISSUE TITLE
TODO: learn Regular Expression

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#38]
## Book

Parsing Techniques - A Practical Guide 2008

## Source Code

- [x] https://github.com/garyhouston/regexp.old
- [x] http://www.cs.princeton.edu/courses/archive/spr09/cos333/beautiful.html
- [x] https://github.com/ldthomas/apg-js2-exp

## Tips

```shell
#用于解析token的正则表达式 
_TOKEN_RE = re.compile( 
#浮点数 
r"""(\d+\.?\d*[eE][+-]?\w+|""" + r"""\.\d+[eE][+-]?\w+|""" + r"""\d+\.\w*|""" + r"""\.\d\w*)|""" + 
#符号 
r"""(!=|==|<<=|<<|<=|>>=|>>|>=|[-%^&*+|/]=|&&|\|\||\+\+|--|\W)|""" +
 #整数 
r"""(\d\w*)|""" +
 #词，关键字或标识符
 r"""([a-zA-Z_]\w*)""") 
```

## Tools

http://www.regexbuddy.com/

**Comment by sabertazimi** [comment]
merge into #45
