### ISSUE TITLE
TODO: algorithms online learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#42]
- [x] online learning - Algo + DS tabs http://www.geeksforgeeks.org/
- [x] List of Algorithms - https://en.m.wikipedia.org/wiki/List_of_algorithms
- [x] [排序算法可视化](http://visualgo.net/sorting.html#)
- [x] [算法可视化](https://github.com/parkjs814/AlgorithmVisualizer)
