### ISSUE TITLE
TODO: Compiler Advanced Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#45]
### Manual
- [x] http://lotabout.me/2015/write-a-C-interpreter-0/
### Lab
- [x] forked repo - c4 compiler
- [x] 知乎 C 收藏 -  https://www.zhihu.com/question/28249756
## Lisp Compiler
- [x] https://ksco.gitbooks.io/build-your-own-lisp/content/
- [x] [Lispy TODO List](https://github.com/sabertazimi/hust-lab/blob/master/compilers/lispy/README.md)

## Write scheme in haskell

- [ ] https://upload.wikimedia.org/wikipedia/commons/a/aa/Write_Yourself_a_Scheme_in_48_Hours.pdf

## JavaScript Engines

- [ ] https://github.com/thinkermao/LL-Script
- [ ] https://github.com/a0viedo/demystifying-js-engines
- [ ] http://rednaxelafx.iteye.com/blog/492667
- [ ] http://hllvm.group.iteye.com/group/topic/37596

### ESTree

- [ ] https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API
- [ ] https://github.com/estree/estree
- [ ] https://github.com/ternjs/acorn
- [ ] https://github.com/davidbonnet/astring
- [ ] https://github.com/estools
- [ ] http://www.w2bc.com/article/186888
- [ ] http://octman.com/blog/2016-08-27-babel-notes/

## Markdown Render

- [ ] https://zhuanlan.zhihu.com/p/24489554?utm_source=cn.ticktick.task&utm_medium=social

## De-compiler

- [ ] https://github.com/dennis714/random_notes/tree/master/toy%20decompiler

## Templates Rendering Engine

*   HTML(Blade)
*   Markdown Rendering Engine

### Book
- [ ] Parsing Techniques - A Practical Guide 2008
- [ ] http://rapidjson.org/zh-cn/md_doc_internals.html#IterativeParserGrammar
### Source Code
- [ ] https://github.com/garyhouston/regexp.old
- [ ] http://www.cs.princeton.edu/courses/archive/spr09/cos333/beautiful.html
- [ ] https://github.com/ldthomas/apg-js2-exp
### Tips

``` shell
#用于解析token的正则表达式 
_TOKEN_RE = re.compile( 
#浮点数 
r"""(\d+\.?\d*[eE][+-]?\w+|""" + r"""\.\d+[eE][+-]?\w+|""" + r"""\d+\.\w*|""" + r"""\.\d\w*)|""" + 
#符号 
r"""(!=|==|<<=|<<|<=|>>=|>>|>=|[-%^&*+|/]=|&&|\|\||\+\+|--|\W)|""" +
 #整数 
r"""(\d\w*)|""" +
 #词，关键字或标识符
 r"""([a-zA-Z_]\w*)""") 
```
### Tools

- [ ] http://www.regexbuddy.com/
- [ ] http://www.regexr.com/
