### ISSUE TITLE
TODO: Advanced Linux C/C++ Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#46]
- [x] http://conanblog.me/Unix-as-IDE--Chinese-/
- [ ] 一站式学习 Linux C/C++ 编程 - http://songjinshan.com/akabook/
- [ ] [Linux/book/advanced linux programming](http://advancedlinuxprogramming.com/alp-folder/)

## Linux

- [ ] [Linux Insides](https://github.com/MintCN/linux-insides-zh)

## Style

- [ ] c/books/短码之美

## Tiny Proj

- [ ] http://www.zhihu.com/question/23844552/answer/91887947

**Comment by sabertazimi** [comment]
merge into #89
