### ISSUE TITLE
TODO: Learning Principles

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#49]
### Basic

- [x] Published Books
- [x] MOOC
- [x] Online Offical Documents
- [x] [CLI Workshop](https://github.com/workshopper/workshopper)   e.g learnyounode
- [x] [Koans](https://github.com/search?o=desc&q=koans&s=stars&type=Repositories&utf8=%E2%9C%93)

### GitHub

- [x] GitHub Awesome Notes/Tips
- [x] GitHub Following Blogs/Repos

#### Javascript

- [x] https://github.com/ruanyf/webpack-demos

### Awesome Tips

- [x] [Top StackOverflow Question](http://hewgill.com/~greg/stackoverflow/ebooks/)
- [x] [Cheet-Sheets.org](http://www.cheat-sheets.org/)
