### ISSUE TITLE
TODO: Workshop for Vim

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#50]
- [x] https://github.com/jez/vim-as-an-ide
- [x] https://github.com/mhinz/vim-galore
- [x] :vimtutor
- [x] https://book.douban.com/subject/4851107/#!/ckDefault
