### ISSUE TITLE
TODO: Workshop for Node Express and MongoDB

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/Awesome-Notes#51]
- [ ] https://github.com/workshopper/learnyounode
- [ ] https://github.com/azat-co/expressworks
- [ ] https://github.com/evanlucas/learnyoumongo
