### ISSUE TITLE
TODO:  CSS Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#54]
## Basic
- [ ] css/books/CSS 权威指南
- [ ] css 揭秘
- [ ] css/books/[CSS 禅意花园](https://github.com/mezzoblue/csszengarden.com)
- [ ] << CSS Mastery >> Book - Deserve Reading
- [ ] 图解CSS3：核心技术与案例实践
- [ ] css secrets
- [ ] css in js - [styled components](https://github.com/styled-components/styled-components)
## Labs
- [ ] https://github.com/NamPNQ/You-Dont-Need-Javascript
- [ ] https://css-tricks.com/building-resizeable-components-relative-css-units/?utm_source=CSS-Weekly&utm_campaign=Issue-230&utm_medium=email
- [ ] https://tympanus.net/codrops2016/
## Style Guide
- [x] http://maintainablecss.com/
## CSS Degisn
- [ ] http://ant-tool.github.io/
- [ ] https://github.com/ant-design/ant-design
- [ ] https://github.com/ant-design/antd-init
## CSS Processor
- [x] [SASS](https://scotch.io/tutorials/getting-started-with-sass)
  -   Variable
  -   Mixins
  -   Nested Class
  -   Extend
  -   Functions
  -   Snippets
- [x] postCSS - Autoprefixer
### flexbox
- [x] http://www.flexboxpatterns.com/home
### Basic
- [ ] http://cssicon.space/#/
- [ ] http://usewing.ml/
- [ ] https://github.com/matt-harris/outline(Sass)
- [ ] https://github.com/ThaoFramework/Thao(Less)
### Layout
- [x] grid system
### CSS Style
- [ ] ari- 前缀
- [ ] data- 前缀
- [ ] -xs/sm/md/lg 后缀
- [ ] -primary/info 后缀
- [ ] active
- [ ] collapse
### Components
- [ ] navbar-前缀
- [ ] carousel
