### ISSUE TITLE
TODO: Web Application Development with JavaScript and MongoDB

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#6]
- [x] gitbook.io/meteor
- [x] http://wiki.jikexueyuan.com/project/discover-meteor/
- [x] To complete mooc on [Coursera](https://www.coursera.org/learn/web-application-development/home/welcome)

**Comment by sabertazimi** [comment]
Merge into #17
