### ISSUE TITLE
TODO: IFE Stage Two - JavaScript Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#61]
- [x] http://www.oschina.net/translate/learning-javascript-design-patterns?print
- [x] https://developer.mozilla.org/zh-CN/docs/Web/Guide/HTML/Forms
- [x] [Read Other Team Source Files](http://ife.baidu.com/task/all) https://github.com/DragonForker
