### ISSUE TITLE
TODO: CSS Design/Style/Theme Basic

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#62]
- [x] http://ant-tool.github.io/
- [x] https://github.com/ant-design/ant-design
- [x] https://github.com/ant-design/antd-init

> Design My Own Theme.

**Comment by sabertazimi** [comment]
merge into #54
