### ISSUE TITLE
TODO: ES 2015/ES 6

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#64]
## Library

- [x] https://github.com/ruanyf/es6tutorial ES 6 标准入门 2015

## Online

- [x] http://www.open-open.com/lib/view/open1447222864319.html
- [x] https://github.com/lukehoban/es6features
- [x] https://github.com/timoxley/functional-javascript-workshop
- [x] https://leanpub.com/understandinges6/read/
- [x] https://github.com/DrkSephy/es6-cheatsheet

### Generator

- [x ] http://greim.github.io/gen/dist/00-intro.html

**Comment by sabertazimi** [comment]
merge into #30
