### ISSUE TITLE
TODO: Aweome-Notes/Web/JavaScript/Demo/Tips-Utils.js

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#65]
-   [ ] master tricks in Tips-Utils.js
-   [ ] merge Tips-Utils.js / JavaScriptBasic.md into utils.js and wrapper them into api/lib
-   [ ] https://github.com/myst729/JavaScript-Utilities
-   [ ] https://github.com/dleitee/strman
-   [ ] JSBasic.md/JSAdvanced.md
-   [ ] You don't need jQuery
-   [ ] 使用 ES6 编写此库 Dragonjs

**Comment by sabertazimi** [comment]
Move to sabertazimi/dragonjs
