### ISSUE TITLE
TODO: Nodejs and Full Stack Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#67]
### Nodejs Basic
- [ ] https://medium.freecodecamp.org/the-definitive-node-js-handbook-6912378afc6e
- [ ] https://blog.risingstack.com/node-hero-tutorial-getting-started-with-node-js/
- [ ] 朴灵 book
- [ ] http://wiki.jikexueyuan.com/project/nodejs-guide/
- [ ] http://course.tianmaying.com/node
- [ ] http://wiki.jikexueyuan.com/project/express-mongodb-setup-blog/
### Nodejs Advanced
- [ ] https://github.com/yjhjstz/deep-into-node
### Nodejs Stream
- [ ] https://github.com/maxogden/bytewiser
- [ ] https://github.com/substack/stream-adventure
### Nodejs Logger
- [ ] https://strongloop.com/strongblog/compare-node-js-logging-winston-bunyan/?_ga=1.264536015.1196661681.1453521338
- [ ] https://strongloop.com/strongblog/robust-node-applications-error-handling/?_ga=1.24936442.1196661681.1453521338
### Nodejs Deploy

http://cnodejs.org/topic/56a3c8f47ec020ed4b96b2cd
-     设置NODE_ENV为“production”
- [ ] 确保应用的自动重启 http://strong-pm.io/compare/?_ga=1.20403576.1196661681.1453521338
-     将应用部署一个集群中
-     缓存请求结果
- [ ] 使用负载均衡 http://socket.io/docs/using-multiple-nodes/#
-     使用反向代理
#### Npm Security

Shell scripts in modules get root priviledge and can do anything.
##### Solution
- [npm-shrinkwrap](https://github.com/uber/npm-shrinkwrap) to lock down your dependencies
- 禁止运行该 module 附带的 shell 脚本

``` shell
npm install someModule --ignore-scripts. 
```
### Node.js Lab
- [ ] http://nodeschool.io/
## Full Stack Learning
- [ ] http://i5ting.github.io/nodejs-fullstack/
- [ ] phodal/growth
