### ISSUE TITLE
TODO: Learn Bootstrap Source Code

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#68]
## Basic

- [x] https://github.com/matt-harris/outline(Sass)
- [x] https://github.com/ThaoFramework/Thao(Less)

## Layout

- [x] grid system

## CSS Style

- [x] ari- 前缀
- [x] data- 前缀

- [x] -xs/sm/md/lg 后缀
- [x] -primary/info 后缀

- [x] active
- [x] collapse

## Components

- [x] navbar-前缀
- [x] carousel

**Comment by sabertazimi** [comment]
merge into #54
