### ISSUE TITLE
TODO: Bower/Npm && Grunt/Gulp Basic

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#69]
-   Bower 前端包管理 水平依赖
-   Npm 后端包管理 树形依赖

-  bowerify/webpack

### Gulpfile.js

- [ ] https://github.com/Platform-CUF/use-gulp
- [ ] https://github.com/eduardolundgren/tracking.js/blob/master/gulpfile.js
- [ ] https://github.com/nimojs/gulp-demo/blob/master/gulpfile.js

**Comment by sabertazimi** [comment]
It's not the time to learn such bundle of things
