### ISSUE TITLE
TODO: React Source Code Deep Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#71]
### Tutorials

- [ ] https://twiknight.gitbooks.io/blog/content/index.html
- [ ] http://purplebamboo.github.io/2015/09/15/reactjs_source_analyze_part_one/
- [ ] [专栏 - purerender: React源码剖析系列](https://segmentfault.com/blog/purerender)
- [ ] https://github.com/acdlite/react-fiber-architecture

**Comment by sabertazimi** [comment]
merge into #11
