### ISSUE TITLE
TODO: Source Code Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#76]
## List

- [ ] https://github.com/aosabook/500lines

### Nodejs

- [ ] https://lovin0730.github.io/2017/01/08/express-core/

### Http

- [ ] https://github.com/EZLippi/Tinyhttpd | https://github.com/cbsheng/tinyhttpd
- [ ] https://github.com/yoshuawuyts/choo
- [x] [Tiny React](https://github.com/developit/preact)

### JavaScript Frameworks

- [ ] [Cash - jQuery Lite](https://github.com/kenwheeler/cash/blob/master/dist/cash.js)
- [ ] [Real MVC](https://github.com/petermichaux/maria)
- [ ] [MVVM](https://zhuanlan.zhihu.com/p/24475845?utm_source=cn.ticktick.task&utm_medium=social)
- [ ] [简约 React-Like 框架](https://zhuanlan.zhihu.com/p/24007986)
- [ ] [Vue-Like](https://zhuanlan.zhihu.com/p/24435564?utm_source=cn.ticktick.task&utm_medium=social)
- [ ] [Mini Redux](https://zapier.com/engineering/how-to-build-redux/?utm_source=javascriptweekly&utm_medium=email)
- [ ] [Mini Redux](https://gist.github.com/jdeal/c224026df3bae5803fd9e58cbbd4a60b/)

#### Virtual DOM

- [ ] https://medium.com/@rajaraodv/the-inner-workings-of-virtual-dom-666ee7ad47cf#.dploayll6
- [ ] https://github.com/trueadm/t7
- [ ] https://github.com/patrick-steele-idem/morphdom/blob/master/src/index.js
- [ ] https://github.com/livoras/blog/issues/13#issue-118253129

### Javascript Modular Pattern

- [ ] https://github.com/seajs/seajs
- [ ] https://github.com/MarkoCen/trial-js

### Parser

- [ ] https://github.com/kbranigan/cJSON

### Compiler

- [x] https://github.com/thejameskyle/the-super-tiny-compiler
- [x] https://github.com/rswier/c4
- [ ] https://github.com/drh/lcc

## Haskell

- [ ] https://github.com/xmonad/xmonad
