### ISSUE TITLE
TODO: GitHub Book Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#77]
- [x] https://github.com/vhf/free-programming-books
- [x] https://github.com/justjavac/free-programming-books-zh_CN

## Font-End

- [x] https://github.com/icepy/Front-End-Develop-Guide
- [x] https://github.com/JacksonTian/fks

## Full Stack

- [x] https://github.com/phodal/growth-ebook

### Operating System

- [x] https://github.com/SamyPesse/How-to-Make-a-Computer-Operating-System
- [x] [内存管理](https://github.com/shellphish/how2heap)

## Algorithms

- [x] https://github.com/haoel/leetcode
