### ISSUE TITLE
TODO: Algorithms Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#88]
## Books
- [x] clrs
- [x] 编程珠玑
- [x] 算法入门经典(刘汝佳)
- [x] 算法(Java实现)
- [x] Tp 311.1.199 挑战程序设计竞赛

## Mooc
- [x] Princeton - Introduction to Algorithms
- [x] Coursera - Standford, Algorithm Analysis
## LeetCode OJ
- [ ] https://leetcode.com
- [ ] http://algorithm.yuanbin.me/zh-hans/index.html
- [x] https://siddontang.gitbooks.io/leetcode-solution/content/array/remove_element.html
- [x] http://www.jiuzhang.com/solutions/
### C++
- [ ] https://siddontang.gitbooks.io/leetcode-solution/content/array/remove_element.html
- [ ] https://github.com/pezy/LeetCode
- [ ] https://github.com/haoel/leetcode
- [ ] https://github.com/illuz/leetcode
## Other OJ
-    [ ] codewars - haskell
-    [ ] codeforces
-    [ ] 牛客网
-    [ ] hackRank
-    [ ] codeFights
-    [x] topCoder
