### ISSUE TITLE
TODO: Linux Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#89]
## Linux Basic

- [ ] read the book Linux/book
- [ ] ‌Traceroute
- [ ] ipconfig
- [ ] nslookup
- [ ] htop/task manager
- [ ] nmap
- [x] https://github.com/jlevy/the-art-of-command-line/blob/master/README-zh.md

## Makefile Learning

- [ ] [Offical Documents](http://www.gnu.org/software/make/manual/make.html)
- [ ] [GitHub following RuanYiFeng](http://www.ruanyifeng.com/blog/2015/02/make.html)

## Shell Learning

- [ ] [HackerRank OJ](https://www.hackerrank.com/domains/shell/textpro/page:1)
- [ ] http://billie66.github.io/TLCL/book/index.html
- [ ] [Linux Bash Cookbook](https://github.com/8ubble/Linux-Books-Pictures)
- [ ] Book: Bash One-Liners Explained
- [ ] Book: linux 101 hacks
- [ ] Book: vim 101 hacks
- [ ] Book: bash 101 hacks

## Linux C

- [x] http://conanblog.me/Unix-as-IDE--Chinese-/
- [ ] [C语言接口技术与实现](http://item.m.jd.com/product/10354393.html)
- [ ] 一站式学习 Linux C/C++ 编程 - http://songjinshan.com/akabook/
- [ ] [Linux/book/advanced linux programming](http://advancedlinuxprogramming.com/alp-folder/)

### Labs

- [ ] http://www.zhihu.com/question/23844552/answer/91887947

## Linux Kernel

- [ ] [Xuetanx/Netease Mooc]()
- [ ] [Linux Insides](https://github.com/MintCN/linux-insides-zh)
- [ ] (Linux Insides EN](https://0xax.gitbooks.io/linux-insides/content)
- [ ] [Linux内核完全注释](https://book.douban.com/subject/1231236/)
- [ ] [Linux内核完全剖析](https://book.douban.com/subject/3229243/)
- [ ] [Linux内核编程](https://book.douban.com/subject/1879461/)
- [ ] [Linux内核设计与实现](https://book.douban.com/subject/6097773/)
- [ ] [深入Linux内核架构](https://book.douban.com/subject/4843567/)
