### ISSUE TITLE
TODO: JS-Books-Patterns/Advaned

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#9]
-   [x] Web/JavaScript/book/High Performance js 2013
- [x] Effective JavaScript 2015

- 合并，压缩 jsfiles
- 暂存对象的attribute e.g Array.length
- 减少DOM操作

-   [x] [/Web/JS/book/js design patterns(online reading)](http://www.oschina.net/translate/learning-javascript-design-patterns?print)
-   [x] https://github.com/fouber/blog
-   [x] https://github.com/feross/standard
- [x] https://github.com/revolunet/JSbooks
