### ISSUE TITLE
TODO: Awesome Mooc

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#90]
- [ ] 华盛顿 programming language
- [ ] 马里兰 software security
- [x] Princeton 算法导论
- [x] http://www.icourse163.org/course/zju-93001#/info
- [ ] https://www.coursera.org/course/optimization
- [ ] https://www.coursera.org/specializations/biancheng-suanfa?utm_source=catalog
- [ ] encrptying
- [ ] algorithms analysis(stanford)
