### ISSUE TITLE
TODO: H5/CSS3/HTTP brand new API

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#92]
### svg
- [ ] http://blog.goguardian.com/nerds/an-odyssey-to-find-a-sustainable-icon-system-with-svgs-in-react
- [ ] http://thenewcode.com/1090/Make-an-Advanced-Adaptive-Branding-Module-with-SVG-amp-JavaScript
- [ ] https://github.com/greensock/GreenSock-JS
### Service worker
- [ ] https://github.com/lyzadanger/pragmatist-service-worker
### H5 Canvas
- [ ] http://joshondesign.com/p/books/canvasdeepdive/toc.html
- [ ] http://codepen.io/idiotWu/pen/AXgbWy
### Offine Application
- [ ] https://github.com/pazguille/offline-first
### Web Audio
- [ ] [Web Audio API CookBook](http://chimera.labs.oreilly.com/books/1234000001552/index.html)
- [ ] [Learning List](https://sonoport.github.io/learning-web-audio-api.html)
### web components

bundle with shadow dom ,html templates, custom elements and html import
- [ ] https://adactio.com/journal/11052
- [ ] https://www.youtube.com/watch?v=fqULJBBEVQE&feature=youtu.be

``` html
<element name="x-foo-shadow" constructor="XFooShadow">
    <template>
        <style>
            @host {
                * {
                        display: block;
                        background: #fc0;
                   }
            }
        </ style>
        <section>I'm an x-foo-shadow. Gots me some Shadow DOM!</ section>
    </ template>
    <script>
        let template = this.querySelector('template');
        this.register({
            prototype: {
                readyCallback: function() {
                    this.createShadowRoot().appendChild(template.content.cloneNode(true));
                }
            }
        });
    </ script>
</ element>
```
#### custom elements
- [ ] [The case for custom elements part 1](https://medium.com/dev-channel/the-case-for-custom-elements-part-1-65d807b4b439#.4l69b1yto)
- [ ] [The case for custom elements part 2](https://medium.com/dev-channel/the-case-for-custom-elements-part-2-2efe42ce9133#.sbecojbci)
-   <element></ element> tag
-   vanilla js method: document.register()

``` js
class ChatFormProto extends HTMLelement {
    attachedCallback() {
    }
    createdCallback() {
    }
    detachedCallback() {
    }
}

document.registerElement('chat-form', ChatFormProto);
```

``` html
<chat-form></ chat-form>
```
### content security policy
- [ ] https://w3c.github.io/webappsec-csp/2/
- [ ] https://webkit.org/blog/6830/a-refined-content-security-policy/
### Http/2

The key features or differences from the old version ofHTTP/1.1 include:
-    Binary instead of Textual - frames and streams:
  -   A collection of frames is called a Stream(unique stream ID)
  -   headers frame + data frame( HEADERS, DATA,RST_STREAM, SETTINGS,PRIORITY frame)
-   Multiplexing - Multiple asynchronous HTTP requests over a single connection
-   Server Push - Multiple responses for single request
-   Header compression using HPACK - Huffman code
-   Request Prioritization
-   Security
#### http 1.1

persistent connection:
-    Client know content-length
-    Chunked encoding: last chunk marked as 0 content-length(Transfer-Encoding: chunked)
#### server push

rather than waiting for the client to send a request, the server preemptively pushes a resource that it predicts the client will request soon afterwards.
- [ ] https://docs.google.com/document/d/1K0NykTXBbbbTlv60t5MyJvXjqKGsCVNYHyLEXIxYMv0/edit
### service worker
- [ ] https://jakearchibald.com/2016/service-worker-meeting-notes/
