### ISSUE TITLE
TODO: Web Security Learning

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#95]
## Basic

- [x] [TCP/IP 1](https://book.douban.com/subject/1088054/)
- [x] [TCP/IP 2](https://book.douban.com/subject/1087767/)
- [x] [TCP/IP 3](https://book.douban.com/subject/1058634/)

## Need

- [x] [Web安全深度剖析](https://book.douban.com/subject/26348894/)
- [x] [精通脚本黑客](https://book.douban.com/subject/2112672/)

## Book

- [x] https://github.com/evilcos/papers
- [x] https://github.com/FallibleInc/security-guide-for-developers

## Advanced

- [x] 白帽子讲Web安全
- [x] Web前端黑客技术揭秘
- [x] 黑客攻防技术宝典(第2版)
- [x] XSS跨站脚本攻击剖析与防御
- [x] SQL注入攻击与防御(第2版)
- [x] Metasploit渗透测试指南
- [x] Metasploit渗透测试魔鬼训练营

**Comment by sabertazimi** [comment]
Merge into #30
