### ISSUE TITLE
TODO: CSS Rendering and DOM Layout in Browser

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#97]
- [x] [Zhihu Reference List](https://www.zhihu.com/question/23679877)
- [x] [CSS Specifications](https://www.w3.org/Style/CSS/read)
- [x] http://www.phpied.com/rendering-repaint-reflowrelayout-restyle/

**Comment by sabertazimi** [comment]
merge into #98
