### ISSUE TITLE
TODO: Browser under the hood

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/awesome-notes#98]
## Basic Browser Workflow
- [ ] http://www.html5rocks.com/en/tutorials/internals/howbrowserswork/
- [ ] http://blogs.adobe.com/webplatform/2013/01/21/getting-started-with-the-webkit-layout-code/
- [ ] http://blogs.adobe.com/webplatform/2013/02/05/a-visual-method-for-understanding-webkit-layout/
## Layout/CSS Rendering
- [ ] [Zhihu Reference List](https://www.zhihu.com/question/23679877)
- [ ] [CSS Specifications](https://www.w3.org/Style/CSS/read)
- [ ] http://www.phpied.com/rendering-repaint-reflowrelayout-restyle/
## Labs
- [ ] https://limpet.net/mbrubeck/2014/08/08/toy-layout-engine-1.html

**Comment by sabertazimi** [comment]
merge into #35
